{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sauce-connect.serviceAccountName" . }}
  labels:
{{ include "sauce-connect.labels" . | indent 4 }}
{{- end -}}
